/*
 * Copyright (c) 2024 The ZMK Contributors
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef RAVEN_IMAGES_H
#define RAVEN_IMAGES_H
#ifdef __cplusplus
extern "C" {
#endif
#include "lvgl.h"

// -------- Image Descriptors Declarations --------
// Replace these with your actual LVGL image data generated by lvgl_img_converter.py
LV_IMG_DECLARE(raven_idle);
LV_IMG_DECLARE(raven_mouth_open);
LV_IMG_DECLARE(raven_wings_open);

// -------- Array of Pointers to Image Descriptors --------
// Provides easy access to all images defined in the corresponding .c file
const lv_img_dsc_t *raven_images[3] = {
    &raven_idle,
    &raven_mouth_open,
    &raven_wings_open,
};

#define RAVEN_IMAGES_NUM_IMAGES 3

#ifdef __cplusplus
}
#endif
#endif /* RAVEN_IMAGES_H */
